### ISSUE TITLE
Imported posts have wrong date

### ISSUE THREAD

**Issue by astray-heavy-arms** [istogram/wp-api-content-migration#1]
When you import posts, the publish date is set to "today/now" and not the date of the post itself when it was published.

**Comment by astray-heavy-arms** [comment]
https://github.com/istogram/wp-api-content-migration/blob/281cf78881751e7cffd507d3d39a8ccba52b0542/src/ContentMigration.php#L375

post_date is missing so it defaults to the current time.

**Comment by timosz** [comment]
@astray-heavy-arms thanks for spotting this! Issue is now fixed.
