### ISSUE TITLE
Importing svg images

### ISSUE THREAD

**Issue by astray-heavy-arms** [istogram/wp-api-content-migration#2]
This one is a bit tricky. If a media gallery contains svg images then: -

https://github.com/istogram/wp-api-content-migration/blob/9b55e6253ce6952f1409d382001a06dac3923e1d/src/ContentMigration.php#L89

createMedia will fail because WP "security" disables importing svgs (I've been trying to sort this myself locally but I've tried everything nothing works for me). 

Allowing unfiltered uploads + adding svg to mime types fails.

**Comment by timosz** [comment]
@astray-heavy-arms thanks for pointing out this issue. This is now fixed by enabling the new config option that allows the uploads of svg media files.
